### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/edges/dep_ewt/en_ewt-ud-dev.json.retokenized.nyu-mll/roberta-base-1B-3'

### ISSUE THREAD

**Issue by 1029694141** [nyu-mll/pretraining-learning-curves#2]
i have input the three command before python probing/retokenize_edge_data.py -t nyu-mll/roberta-base-1B-3  data/edges/dep_ewt/*.json  in order 。 Thanks for ur help!

**Comment by YianZhang** [comment]
Hi,

Thank you for raising this issue! What is the commit ID of the jiant repo you are using to reproduce our work? Checking-out a7fdd0d8203453b451d9cc54ccac9561b73e9fb8 might solve the problem if you used an outdated version of jiant1.

**Comment by 1029694141** [comment]
Thank you for your reply！
I used this command before，(`git clone --branch v1.3.2  --recursive https://github.com/nyu-mll/jiant.git jiant`)
Now I have listened to your suggestions and I have used the new version[ jian](https://github.com/nyu-mll/jiant-v1-legacy) 。

Thank you again for your help and wish you all the best！
